Fix crash caused by realpath()'s "/." return
thread '<unnamed>' (986402) panicked at src/fstree.rs:63:17:
Unable to walk path "/home/mao/code/.": dots are not allowed
stack backtrace:
   0:     0x55e8efd81311 - <<std[45c109d77f3943b3]::sys::backtrace::BacktraceLock>::print::DisplayBacktrace as core[4489dfa0202797d1]::fmt::Display>::fmt
   1:     0x55e8efd98dfa - core[4489dfa0202797d1]::fmt::write
   2:     0x55e8efd87bcc - <std[45c109d77f3943b3]::sys::stdio::unix::Stderr as std[45c109d77f3943b3]::io::Write>::write_fmt
   3:     0x55e8efd62a56 - std[45c109d77f3943b3]::panicking::default_hook::{closure#0}
   4:     0x55e8efd7b3b1 - std[45c109d77f3943b3]::panicking::default_hook
   5:     0x55e8efd7b6db - std[45c109d77f3943b3]::panicking::panic_with_hook
   6:     0x55e8efd62b02 - std[45c109d77f3943b3]::panicking::panic_handler::{closure#0}
   7:     0x55e8efd5a229 - std[45c109d77f3943b3]::sys::backtrace::__rust_end_short_backtrace::<std[45c109d77f3943b3]::panicking::panic_handler::{closure#0}, !>
   8:     0x55e8efd6332d - __rustc[54af582dd63377fb]::rust_begin_unwind
   9:     0x55e8efd996ac - core[4489dfa0202797d1]::panicking::panic_fmt
  10:     0x55e8efbbe146 - <libturnstile[b5c10a0de16bee6a]::fstree::PathToComponentsIter as core[4489dfa0202797d1]::iter::traits::iterator::Iterator>::next
                               at /home/mao/code/libturnstile/src/fstree.rs:63:5
  11:     0x55e8efba5ed9 - <libturnstile[b5c10a0de16bee6a]::fstree::FsTree<libturnstile[b5c10a0de16bee6a]::sandbox::managed_bind_mount_sandbox::MountInternal>>::find::<<libturnstile[b5c10a0de16bee6a]::sandbox::managed_bind_mount_sandbox::ManagedBindMountSandbox>::covering_mount::{closure#0}>
                               at /home/mao/code/libturnstile/src/fstree.rs:311:15
  12:     0x55e8efbcbd0a - <libturnstile[b5c10a0de16bee6a]::sandbox::managed_bind_mount_sandbox::ManagedBindMountSandbox>::covering_mount
                               at /home/mao/code/libturnstile/src/sandbox/upgrade.rs:289:5
  13:     0x55e8efbc8994 - <libturnstile[b5c10a0de16bee6a]::sandbox::managed_bind_mount_sandbox::ManagedBindMountSandbox>::handle_chdir
                               at /home/mao/code/libturnstile/src/sandbox/upgrade.rs:797:52
  14:     0x55e8efbca638 - <libturnstile[b5c10a0de16bee6a]::sandbox::managed_bind_mount_sandbox::ManagedBindMountSandbox>::allow_request
                               at /home/mao/code/libturnstile/src/sandbox/upgrade.rs:473:16
  15:     0x55e8efba10b7 - <libturnstile[b5c10a0de16bee6a]::sandbox::upgrade::RequestHandle>::allow
                               at /home/mao/code/libturnstile/src/sandbox/upgrade.rs:77:16
  16:     0x55e8ef821a93 - turnstile_sandbox[b95932231192d1a7]::tracing_thread
                               at /home/mao/code/libturnstile/src/bin/turnstile-sandbox.rs:1465:13

Signed-off-by: Tingmao Wang <m@maowtm.org>